packages:
  - packages/**
  - examples/**

allowBuilds:
  "@swc/core": true
  esbuild: true

catalog:
  "@types/node": "^25.6.0"
  tsdown: "^0.21.10"

engineStrict: true
strictPeerDependencies: true
shellEmulator: true
preferWorkspacePackages: true
linkWorkspacePackages: true
enablePrePostScripts: true
