packages:
  - packages/**
  - examples/**

allowBuilds:
  "@swc/core": true
  esbuild: true

catalog:
  "@types/node": "^24.6.2"
  tsdown: "^0.21.6"

engineStrict: true
strictPeerDependencies: true
shellEmulator: true
preferWorkspacePackages: true
linkWorkspacePackages: true
enablePrePostScripts: true
